name: pokemonmacros
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.5.0-152 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1  
  json: ^0.20.1
  http: ^1.2.1
  #
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
